#!/usr/bin/env bash
# tests/snapshot-baselines.sh
#
# Regenerate baseline manifests from a fresh CTT run.
#
# Usage:
#   ./tests/snapshot-baselines.sh                 # full ctt.toml
#   ./tests/snapshot-baselines.sh ctt-minimal.toml
#
# Run AFTER intentional template changes you've verified are correct.
#
# CTT writes each scenario to <repo_root>/<scenario_key>/ (the output_dir
# setting in ctt.toml is ignored by the upstream tool). This script:
#   1. Parses ctt.toml → list of scenario keys
#   2. Removes any pre-existing scenario directories at root
#   3. Runs ctt
#   4. For each scenario_key: builds tests/baseline/<scenario_key>/manifest.txt
#   5. Updates tests/baseline/INDEX.txt
#   6. Cleans up the scenario directories (leave repo tidy)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

CTT_CONFIG="${1:-ctt.toml}"
BASELINE_DIR="tests/baseline"
INDEX_FILE="$BASELINE_DIR/INDEX.txt"

KEEP_OUTPUTS="${KEEP_OUTPUTS:-0}"   # set to 1 to leave scenario dirs in place
LIMIT="${LIMIT:-0}"                 # set to N to only process first N scenarios (debugging)

echo "==> Snapshot baselines (config: $CTT_CONFIG)"

if [[ ! -f "$CTT_CONFIG" ]]; then
    echo "ERROR: $CTT_CONFIG not found" >&2
    exit 1
fi

if ! command -v ctt >/dev/null 2>&1; then
    echo "ERROR: 'ctt' (copier-template-tester) not found on PATH" >&2
    echo "Install: pipx install copier-template-tester" >&2
    exit 1
fi

# Hasher
if command -v sha256sum >/dev/null 2>&1; then
    HASHER="sha256sum"
else
    HASHER="shasum -a 256"
fi

# Resolve scenario keys (portable; macOS bash 3.2 has no mapfile)
SCENARIOS=()
while IFS= read -r line; do
    SCENARIOS+=("$line")
done < <(python3 tests/lib/scenarios.py "$CTT_CONFIG")
if [[ ${#SCENARIOS[@]} -eq 0 ]]; then
    echo "ERROR: no scenarios found in $CTT_CONFIG" >&2
    exit 1
fi
echo "==> ${#SCENARIOS[@]} scenarios in $CTT_CONFIG"

# Pre-clean any leftovers
for s in "${SCENARIOS[@]}"; do
    [[ -d "$s" ]] && rm -rf "$s"
done

# Run CTT
if [[ "$CTT_CONFIG" != "ctt.toml" ]]; then
    cp ctt.toml ctt.toml.bak.$$
    cp "$CTT_CONFIG" ctt.toml
    trap 'mv ctt.toml.bak.$$ ctt.toml 2>/dev/null || true' EXIT
fi

echo "==> Running ctt (this may take several minutes for the full suite)..."
LOG=$(mktemp)
if ! ctt -b . > "$LOG" 2>&1; then
    echo "ERROR: ctt failed (last 30 lines of log):" >&2
    tail -30 "$LOG" >&2
    exit 1
fi
echo "==> ctt completed; running garden replant on each scenario..."

# CTT renders templates but skips copier _tasks. Run replant manually on
# each scenario directory so baselines reflect the post-task state.
for scenario in "${SCENARIOS[@]}"; do
    [[ -d "$scenario" ]] || continue
    if [[ -f "$scenario/.garden/garden.py" ]]; then
        (cd "$scenario" && python3 .garden/garden.py replant > /dev/null 2>&1) || true
    fi
done

echo "==> processing scenarios into manifests..."

# Build manifests
mkdir -p "$BASELINE_DIR"
{
    echo "# Baseline index — generated by snapshot-baselines.sh"
    printf "# Format: <scenario>\\\\t<total_files>\\\\t<total_bytes>\\\\t<manifest_sha256>\n"
    echo "# DO NOT EDIT — regenerate via ./tests/snapshot-baselines.sh"
} > "$INDEX_FILE"

processed=0
missing=()
for scenario in "${SCENARIOS[@]}"; do
    if [[ "$LIMIT" -gt 0 && "$processed" -ge "$LIMIT" ]]; then
        break
    fi
    if [[ ! -d "$scenario" ]]; then
        missing+=("$scenario")
        continue
    fi

    out_dir="$BASELINE_DIR/$scenario"
    mkdir -p "$out_dir"
    manifest="$out_dir/manifest.txt"

    {
        echo "# Manifest for scenario: $scenario"
        printf "# Format: <sha256>\\\\t<size>\\\\t<relative-path>\n"
        echo "# Sorted by path. Paths relative to scenario root."
        echo "# DO NOT EDIT — regenerate via ./tests/snapshot-baselines.sh"
    } > "$manifest"

    (
        cd "$scenario"
        find . -type f -not -path "./.git/*" -print0 |
            sort -z |
            while IFS= read -r -d '' f; do
                rel="${f#./}"
                size=$(stat -f '%z' "$f" 2>/dev/null || stat -c '%s' "$f" 2>/dev/null || echo "0")
                hash=$($HASHER "$f" | awk '{print $1}')
                printf '%s\t%s\t%s\n' "$hash" "$size" "$rel"
            done
    ) >> "$manifest"

    total_files=$(grep -cv '^#' "$manifest" || echo 0)
    total_bytes=$(grep -v '^#' "$manifest" | awk '{s+=$2} END {print s+0}')
    manifest_hash=$($HASHER "$manifest" | awk '{print $1}')
    printf '%s\t%d\t%d\t%s\n' "$scenario" "$total_files" "$total_bytes" "$manifest_hash" >> "$INDEX_FILE"

    processed=$((processed + 1))
    printf "  [%2d/%d] %-40s %5d files, %10d bytes\n" "$processed" "${#SCENARIOS[@]}" "$scenario" "$total_files" "$total_bytes"
done

# Sort INDEX (keep header)
{
    grep '^#' "$INDEX_FILE"
    grep -v '^#' "$INDEX_FILE" | sort
} > "$INDEX_FILE.sorted"
mv "$INDEX_FILE.sorted" "$INDEX_FILE"

# Cleanup
if [[ "$KEEP_OUTPUTS" != "1" ]]; then
    echo "==> Cleaning up scenario output directories"
    for s in "${SCENARIOS[@]}"; do
        [[ -d "$s" ]] && rm -rf "$s"
    done
fi

echo ""
echo "==> Done. $processed scenarios captured."
if [[ ${#missing[@]} -gt 0 ]]; then
    echo "WARNING: ${#missing[@]} scenarios listed in $CTT_CONFIG produced no output:"
    printf '  - %s\n' "${missing[@]}"
fi
echo "    Index:     $INDEX_FILE"
echo "    Manifests: $BASELINE_DIR/<scenario>/manifest.txt"
